[tool.poetry]
name = "cloudcopy"
version = "0.0.1"
description = "CloudCopy Core: client and server"
authors = ["Anthony Leontiev <ant@devlit.co>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
adbc = "^0.0.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
